### ISSUE TITLE
Not compatible with Hashie 1.0.0

### ISSUE THREAD

**Issue by phw** [dwo/musicbrainz-ruby#1]
Hashie has released a version 1.0.0, but the current musicbrainz-ruby gem requires it with ~> 0.4.0 (hashie(1.0.0 not ~> 0.4.0)).

But seems to work fine with hashie 1.0 otherwise.

**Comment by dwo** [comment]
Thanks for letting me know, it does seem to work. I've changed the dependency and pushed a patch version of the gem.
