### ISSUE TITLE
Enable advanced search functionality

### ISSUE THREAD

**Issue by hjhart** [dwo/musicbrainz-ruby#3]
In my case, I want to be able to have a query that maps to this search:

http://musicbrainz.org/search?query=%22come+back+to+me%22+AND+artist%3A%22the+rapture%22+AND+type%3Aalbum&type=recording&limit=25&advanced=1

The raw query looks like this:

"come back to me" AND artist:"the rapture" AND type:album

I'm thinking that the query would probably look something like this:

brainz.recording(:query => ' "come back to me" AND artist:"the rapture" AND type:album', :advanced => 1)

Notice the string is an exact match as well...

**Comment by dwo** [comment]
hope to support this in the next release

**Comment by dwo** [comment]
I think you should be able to do those advanced query syntax queries with the newer version of the gem, please let me know if it's lacking something that the docs say should be possible: http://musicbrainz.org/doc/Next_Generation_Schema/SearchServerXML
